version: '3.9'

services:
  postgres:
    image: kartoza/postgis:16
    container_name: postgres
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASS: ${DB_PASSWORD}
      POSTGRES_DBNAME: postgres_dev,postgres_prod
      POSTGRES_MULTIPLE_EXTENSIONS: postgis

  minio:
    image: minio/minio:latest
    container_name: minio
    expose:
      - ${MINIO_PORT}
      - "9001"
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

  createbucket:
    container_name: createbucket
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:${MINIO_PORT} root ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc admin user svcacct add --access-key=${MINIO_ACCESS_KEY} --secret-key=${MINIO_SECRET_KEY} myminio root;
      /usr/bin/mc mb myminio/dev;
      /usr/bin/mc anonymous set public myminio/dev;
      /usr/bin/mc mb myminio/prod;
      /usr/bin/mc anonymous set public myminio/prod;
      exit 0;
      "
  blazegraph:
    container_name: blazegraph
    image: bluebrain/blazegraph-nexus:2.1.6-RC
    restart: always
    ports:
      - 9999:9999

  datatourisme:
    container_name: datatourisme
    build: docker
    ports:
        - "8080:80"
    restart: always
    depends_on:
        - blazegraph